const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/data/spells_pt.json');
const spells = JSON.parse(fs.readFileSync(filePath, 'utf8'));

// Translate common field values
function translateCastingTime(v) {
  if (!v) return v;
  return v
    .replace(/1 action/gi, '1 ação')
    .replace(/1 bonus action/gi, '1 ação bônus')
    .replace(/1 reaction/gi, '1 reação')
    .replace(/1 minute/gi, '1 minuto')
    .replace(/10 minutes/gi, '10 minutos')
    .replace(/1 hour/gi, '1 hora')
    .replace(/8 hours/gi, '8 horas')
    .replace(/12 hours/gi, '12 horas')
    .replace(/24 hours/gi, '24 horas')
    .replace(/Special/gi, 'Especial');
}

function translateRange(v) {
  if (!v) return v;
  return v
    .replace(/Self \((\d+)-foot(.*?)\)/gi, (_, d, rest) => `Pessoal (${d} pés${rest.replace(/-foot/g, ' pés').replace(/radius/g, 'raio').replace(/cone/g, 'cone').replace(/line/g, 'linha')})`)
    .replace(/Self/gi, 'Pessoal')
    .replace(/Touch/gi, 'Toque')
    .replace(/Sight/gi, 'Visão')
    .replace(/Unlimited/gi, 'Ilimitado')
    .replace(/Special/gi, 'Especial')
    .replace(/(\d+) feet/gi, (_, d) => `${d} pés`)
    .replace(/(\d+) miles?/gi, (_, d) => `${d} milha${d > 1 ? 's' : ''}`);
}

function translateDuration(v) {
  if (!v) return v;
  return v
    .replace(/Instantaneous/gi, 'Instantânea')
    .replace(/Until dispelled/gi, 'Até ser dissipada')
    .replace(/Concentration,?\s*/gi, 'Concentração, ')
    .replace(/up to (\d+) minutes?/gi, (_, d) => `até ${d} minuto${d > 1 ? 's' : ''}`)
    .replace(/up to (\d+) hours?/gi, (_, d) => `até ${d} hora${d > 1 ? 's' : ''}`)
    .replace(/up to (\d+) rounds?/gi, (_, d) => `até ${d} turno${d > 1 ? 's' : ''}`)
    .replace(/up to (\d+) days?/gi, (_, d) => `até ${d} dia${d > 1 ? 's' : ''}`)
    .replace(/Up to (\d+) minutes?/gi, (_, d) => `Até ${d} minuto${d > 1 ? 's' : ''}`)
    .replace(/Up to (\d+) hours?/gi, (_, d) => `Até ${d} hora${d > 1 ? 's' : ''}`)
    .replace(/Up to (\d+) rounds?/gi, (_, d) => `Até ${d} turno${d > 1 ? 's' : ''}`)
    .replace(/Up to (\d+) days?/gi, (_, d) => `Até ${d} dia${d > 1 ? 's' : ''}`)
    .replace(/(\d+) minutes?/gi, (_, d) => `${d} minuto${d > 1 ? 's' : ''}`)
    .replace(/(\d+) hours?/gi, (_, d) => `${d} hora${d > 1 ? 's' : ''}`)
    .replace(/(\d+) rounds?/gi, (_, d) => `${d} turno${d > 1 ? 's' : ''}`)
    .replace(/(\d+) days?/gi, (_, d) => `${d} dia${d > 1 ? 's' : ''}`)
    .replace(/Special/gi, 'Especial');
}

// Hand-crafted Portuguese descriptions keyed by spell id
const PT_DESCRIPTIONS = {
  // CANTRIPS
  "acid-splash": "Você arremessa uma bolha de ácido. Escolha uma criatura dentro do alcance, ou escolha duas criaturas dentro do alcance que estejam a até 1,5 metro uma da outra. O alvo deve ser bem-sucedido em um teste de resistência de Destreza ou sofre 1d6 de dano ácido.\nO dano deste feitiço aumenta em 1d6 quando você atinge o 5º nível (2d6), o 11º nível (3d6) e o 17º nível (4d6).",
  "chill-touch": "Você cria uma mão fantasmagórica na forma de um esqueleto e a usa para atacar uma criatura dentro do alcance com um toque arrepiante. Faça um ataque mágico à distância contra a criatura. Se acertar, o alvo sofre 1d8 de dano necrótico e não pode recuperar pontos de vida até o início do seu próximo turno. Até lá, a mão se agarra ao alvo.\nSe você acertar um morto-vivo, ele também fica com desvantagem nos rolamentos de ataque contra você até o fim do seu próximo turno.\nO dano aumenta em 1d8 quando você atinge o 5º nível (2d8), o 11º nível (3d8) e o 17º nível (4d8).",
  "dancing-lights": "Você cria até quatro luzes do tamanho de tochas dentro do alcance, fazendo com que pareçam lanternas, tochas ou orbes brilhantes que pairam no ar durante a duração. Você também pode combinar as quatro luzes em uma forma vagamente humanoide de tamanho Médio que brilha suavemente. Qualquer que seja a forma que você escolher, cada luz emite apenas luz fraca em um raio de 3 metros.\nComo uma ação bônus no seu turno, você pode mover as luzes até 18 metros para um novo local dentro do alcance. Uma luz deve estar a até 6 metros de outra luz criada por este feitiço, e a luz se apaga se ultrapassar o alcance do feitiço.",
  "druidcraft": "Você sussurra os segredos da natureza. Você cria um dos seguintes efeitos mágicos dentro do alcance:\n• Você cria um efeito climático que prevê o clima nos próximos 24 horas.\n• Você faz uma flor desabrochar, uma semente se abrir, ou uma folha brotar.\n• Você cria um efeito sensorial inofensivo que evoca a natureza, como folhas caindo, uma brisa suave, o barulho de um pequeno animal, ou o leve cheiro de uma flor.\n• Você acende ou apaga instantaneamente uma vela, uma tocha ou uma pequena fogueira.",
  "eldritch-blast": "Um raio de energia crepitante risca em direção a uma criatura dentro do alcance. Faça um ataque mágico à distância contra a criatura. Se acertar, o alvo sofre 1d10 de dano de força.\nO feitiço cria mais de um raio quando você atinge níveis mais altos: dois raios no 5º nível, três raios no 11º nível e quatro raios no 17º nível. Você pode direcionar os raios para o mesmo alvo ou para alvos diferentes.",
  "fire-bolt": "Você arremessa um fagulha de fogo em direção a uma criatura ou objeto dentro do alcance. Faça um ataque mágico à distância contra o alvo. Se acertar, o alvo sofre 1d10 de dano de fogo. Um objeto inflamável atingido por este feitiço pega fogo se não estiver sendo carregado ou vestido.\nO dano deste feitiço aumenta em 1d10 quando você atinge o 5º nível (2d10), o 11º nível (3d10) e o 17º nível (4d10).",
  "guidance": "Você toca uma criatura voluntária. Uma vez antes do feitiço terminar, o alvo pode rolar um d4 e adicionar o número rolado a um teste de habilidade de sua escolha. Ele pode rolar o dado antes ou depois de fazer o teste de habilidade. O feitiço então termina.",
  "light": "Você toca um objeto de até 3 metros de comprimento. Até o feitiço terminar, o objeto emite luz brilhante em um raio de 6 metros e luz fraca por mais 6 metros. A cor da luz pode ser escolhida por você. Cobrir completamente o objeto com algo opaco bloqueia a luz. O feitiço termina se você o lançar novamente ou o dissipar como uma ação.\nSe você mirar num objeto mantido ou usado por uma criatura hostil, essa criatura deverá ser bem-sucedida em um teste de resistência de Destreza para evitar o feitiço.",
  "mage-hand": "Uma mão espectral e flutuante aparece no ponto que você especificar dentro do alcance. A mão dura durante a duração ou até você a dispensar com uma ação. A mão desaparece se ficar a mais de 9 metros de você ou se você lançar este feitiço novamente.\nVocê pode usar sua ação para controlar a mão. Você pode usá-la para manipular um objeto, abrir uma porta destrancada ou um contêiner, guardar ou recuperar um item de um contêiner aberto, ou despejar o conteúdo de um frasco. Você pode mover a mão até 9 metros por ação. A mão não pode atacar, ativar itens mágicos ou carregar mais de 5 quilos.",
  "mending": "Este feitiço repara uma única ruptura ou fratura em um objeto que você toca, como uma corrente com elo partido, dois pedaços de uma chave quebrada, uma capa rasgada ou um odre com furo. Contanto que a ruptura ou fratura não seja maior do que 30 cm em qualquer dimensão, você conserta deixando nenhum traço visível do dano.\nEste feitiço pode reparar fisicamente um item mágico ou golem, mas não pode restaurar a magia de tal objeto.",
  "message": "Você aponta o dedo para uma criatura dentro do alcance e sussurra uma mensagem. O alvo (e somente ele) ouve a mensagem e pode responder em um sussurro que só você ouvirá.\nVocê pode lançar este feitiço através de objetos sólidos se estiver familiarizado com o alvo e souber que ele está além da barreira. A magia não atravessa silêncio mágico, 30 cm de pedra, 2,5 cm de metal comum, uma fina folha de chumbo ou 90 cm de madeira. O feitiço não precisa seguir uma linha reta e pode viajar livremente em volta dos cantos ou através das aberturas.",
  "minor-illusion": "Você cria um som ou imagem de um objeto dentro do alcance que dura durante a duração. A ilusão também termina se você a dispensar como uma ação ou lançar este feitiço novamente.\nSe você criar um som, seu volume pode variar de um sussurro a um grito. Pode ser sua voz, a de outra pessoa, o rugido de um leão, o barulho de uma batida, ou qualquer outro som que você escolher. O som continua ininterruptamente durante a duração, ou você pode fazer sons discretos em momentos diferentes antes do feitiço terminar.\nSe você criar uma imagem de um objeto — como uma cadeira, pés lamacentos ou um pequeno baú — ela não pode criar som, luz, cheiro ou outros efeitos sensoriais. As criaturas que usam suas ações para examinar o som ou a imagem podem determinar que é uma ilusão com um teste de Inteligência (Investigação) bem-sucedido contra a sua CD de magia. Se uma criatura discernir a ilusão pelo que é, o efeito ilusório se torna apagado para ela.",
  "poison-spray": "Você estende sua mão em direção a uma criatura que você pode ver dentro do alcance e projeta um jato de gás venenoso dela. A criatura deve ter sucesso em um teste de resistência de Constituição ou sofrer 1d12 de dano de veneno.\nO dano deste feitiço aumenta em 1d12 quando você atinge o 5º nível (2d12), o 11º nível (3d12) e o 17º nível (4d12).",
  "prestidigitation": "Este feitiço é um truque mágico que conjuradores novatos usam para praticar. Você cria um dos seguintes efeitos mágicos dentro do alcance:\n• Você cria um efeito sensorial inofensivo e instantâneo, como uma chuva de faíscas, uma lufada de vento, sons suaves, ou um odor peculiar.\n• Você acende ou apaga instantaneamente uma vela, uma tocha ou uma pequena fogueira.\n• Você limpa ou suja instantaneamente um objeto de tamanho não maior que 1 metro cúbico.\n• Você resfria, aquece ou dá sabor a até 1 litro de material não-vivo por 1 hora.\n• Você faz a cor, o sabor ou o cheiro de um objeto não-vivo mudar por 1 hora.\n• Você cria uma marca não-mágica em um objeto ou uma superfície por 1 hora.\nSe você lançar este feitiço várias vezes, você pode ter até três de seus efeitos não-instantâneos ativos ao mesmo tempo, podendo dispensar qualquer efeito como uma ação.",
  "produce-flame": "Uma chama não-inflamável aparece na sua mão. A chama permanece ali durante a duração e não prejudica você nem seu equipamento. A chama emite luz brilhante em um raio de 3 metros e luz fraca por mais 3 metros. O feitiço termina se você o dispensar como uma ação ou se o lançar novamente.\nVocê pode também atacar com a chama, embora isso termine o feitiço. Quando você lançar este feitiço, ou como uma ação em um turno posterior, você pode arremessar a chama em uma criatura dentro de 9 metros de você. Faça um ataque mágico à distância. Se acertar, o alvo sofre 1d8 de dano de fogo.\nO dano aumenta em 1d8 quando você atinge o 5º nível (2d8), o 11º nível (3d8) e o 17º nível (4d8).",
  "ray-of-frost": "Um raio azul-branco de frio intenso sai de seus dedos apontados em direção a uma criatura dentro do alcance. Faça um ataque mágico à distância contra ela. Se acertar, o alvo sofre 1d8 de dano de frio e sua velocidade é reduzida em 3 metros até o início do seu próximo turno.\nO dano deste feitiço aumenta em 1d8 quando você atinge o 5º nível (2d8), o 11º nível (3d8) e o 17º nível (4d8).",
  "resistance": "Você toca uma criatura voluntária. Uma vez antes do feitiço terminar, o alvo pode rolar um d4 e adicionar o número rolado a um teste de resistência de sua escolha. Ele pode rolar o dado antes ou depois de fazer o teste de resistência. O feitiço então termina.",
  "sacred-flame": "A luz semelhante a chamas desce sobre uma criatura que você pode ver dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Destreza ou sofre 1d8 de dano radiante. O alvo não recebe bônus de cobertura para esse teste de resistência.\nO dano deste feitiço aumenta em 1d8 quando você atinge o 5º nível (2d8), o 11º nível (3d8) e o 17º nível (4d8).",
  "shillelagh": "A madeira do cajado ou da clava que você usa ao lançar este feitiço é imbuída com poder da natureza. Por sua duração, você pode usar seu modificador de habilidade de conjuração em vez de Força para jogadas de ataque e dano usando aquela arma, e o dado de dano da arma se torna um d8. A arma também se torna mágica, se não for. O feitiço termina se você lançá-lo novamente ou se a arma for guardada.",
  "shocking-grasp": "O raio elétrico salta de você para uma criatura que você tenta tocar. Faça um ataque mágico corpo a corpo contra o alvo. Você tem vantagem no rolamento de ataque se o alvo estiver usando armadura feita de metal. Se acertar, o alvo sofre 1d8 de dano de relâmpago e não pode usar reações até o início do próximo turno dele.\nO dano deste feitiço aumenta em 1d8 quando você atinge o 5º nível (2d8), o 11º nível (3d8) e o 17º nível (4d8).",
  "spare-the-dying": "Você toca uma criatura viva que tem 0 pontos de vida. A criatura se torna estável. Este feitiço não tem efeito em mortos-vivos ou constructos.",
  "thaumaturgy": "Você manifesta um portento menor, um sinal de poder sobrenatural, dentro do alcance. Você cria um dos seguintes efeitos mágicos dentro do alcance:\n• Sua voz ressoa até três vezes mais alto que o normal por 1 minuto.\n• Você faz chamas vacilarem, ficarem mais brilhantes, mais fracas, ou mudarem de cor por 1 minuto.\n• Você faz tremores inofensivos no chão por 1 minuto.\n• Você cria um som instantâneo que se origina de um ponto de sua escolha dentro do alcance, como um trovão, o grasnar de um corvo, ou sussurros sinistros.\n• Você faz a porta ou janela de que não esteja trancada se abrir ou fechar rapidamente.\n• Você altera a aparência de seus olhos por 1 minuto.\nSe você lançar este feitiço várias vezes, você pode ter até três de seus efeitos de 1 minuto ativos ao mesmo tempo, e pode dispensar tais efeitos como uma ação.",
  "true-strike": "Você estende sua mão e aponta um dedo em direção a um alvo dentro do alcance. Sua magia lhe garante uma visão breve do futuro próximo do alvo — no seu próximo turno, você ganha vantagem no seu primeiro rolamento de ataque contra o alvo, desde que este feitiço ainda esteja ativo.",
  "vicious-mockery": "Você solta um fluxo de insultos entrelaçados com encantamentos sutis em uma criatura que você pode ver dentro do alcance. Se o alvo puder ouvi-lo (ele não precisa entender você), ele deve ser bem-sucedido em um teste de resistência de Sabedoria ou sofre 1d4 de dano psíquico e tem desvantagem no próximo rolamento de ataque que fizer antes do fim do seu próximo turno.\nO dano deste feitiço aumenta em 1d4 quando você atinge o 5º nível (2d4), o 11º nível (3d4) e o 17º nível (4d4).",
  // LEVEL 1
  "acid-arrow": "Uma flecha cintilante e verde risca em direção a um alvo dentro do alcance e explode em um jato de ácido. Faça um ataque mágico à distância contra o alvo. Se acertar, o alvo sofre 4d4 de dano ácido imediatamente e 2d4 de dano ácido no final do seu próximo turno. Se errar, a flecha espirra o alvo com ácido por metade do dano inicial e nenhum dano no final do próximo turno.",
  "aid": "Seu feitiço fortalece seus aliados com resistência e determinação. Escolha até três criaturas dentro do alcance. O máximo de pontos de vida e os pontos de vida atuais de cada alvo aumentam em 5 durante a duração.",
  "alarm": "Você prepara um alarme mágico contra intrusão. Escolha uma porta, uma janela ou uma área dentro do alcance que não exceda um cubo de 6 metros. Até o feitiço terminar, um alarme alerta você sempre que uma criatura Tiny ou maior tocar ou entrar na área vigiada. Quando você lança o feitiço, você pode designar criaturas que não ativarão o alarme. Você também escolhe se o alarme é mental ou audível.\nUm alarme mental acorda você do sono quando ativado. Quando estiver acordado, o alarme mental sussurra em sua mente.\nUm alarme audível produz o som de uma campainha por 10 segundos dentro de 18 metros.",
  "animate-dead": "Este feitiço cria um servo não-morto. Escolha um monte de ossos ou um cadáver de uma criatura humanoide de tamanho Médio ou Pequeno dentro do alcance. Seu feitiço imbuia o alvo com uma centelha sombria de magia negra, levantando-o como um morto-vivo. O alvo se torna um esqueleto se você escolher ossos ou um zumbi se você escolher um cadáver (o Mestre tem as estatísticas de jogo da criatura).\nEm cada um de seus turnos, você pode usar uma ação bônus para controlar mentalmente qualquer criatura que você criou com este feitiço se a criatura estiver dentro de 18 metros de você. Se você controlar várias criaturas, poderá controlar várias delas ao mesmo tempo, dando a cada uma a mesma ordem ou ordens diferentes. Você decide qual ação a criatura tomará e para onde se moverá durante seu próximo turno, ou pode dar uma ordem geral, como guardar uma câmara particular ou um corredor. Se você não der nenhuma ordem, a criatura se defenderá contra criaturas hostis. Uma vez dada uma ordem, a criatura continua a seguir até que a tarefa seja completa.\nA criatura está sob seu controle por 24 horas, após as quais ela para de obedecer a qualquer comando que você der a ela. Para manter o controle da criatura por outras 24 horas, você deve lançar este feitiço na criatura novamente antes que o período de controle de 24 horas atual expire. Este uso do feitiço reatirma seu controle sobre até quatro criaturas que você criou com este feitiço, em vez de animar uma nova.",
  "bane": "Até três criaturas à sua escolha que você possa ver dentro do alcance devem ser bem-sucedidas em testes de resistência de Carisma ou ficam amaldiçoadas durante a duração. Sempre que uma criatura amaldiçoada fizer um rolamento de ataque ou teste de resistência antes do feitiço terminar, ela deverá rolar um d4 e subtrair o número rolado do rolamento de ataque ou do teste de resistência.",
  "bless": "Você abençoa até três criaturas à sua escolha dentro do alcance. Sempre que um alvo fizer um rolamento de ataque ou teste de resistência antes do feitiço terminar, o alvo pode rolar um d4 e adicionar o número ao rolamento de ataque ou ao teste de resistência.",
  "burning-hands": "Ao esticar os polegares e entrelaçar os dedos, você produz uma fina folha de chamas que parte de suas mãos estendidas. Cada criatura em um cone de 4,5 metros deve fazer um teste de resistência de Destreza. Uma criatura que falha sofre 3d6 de dano de fogo, ou metade do dano se tiver êxito. O fogo incendeia qualquer objeto inflamável na área que não esteja sendo carregado ou vestido.",
  "charm-person": "Você tenta encantar um humanoide que você possa ver dentro do alcance. Ele deve fazer um teste de resistência de Sabedoria, e o faz com vantagem se você ou seus companheiros estiverem lutando com ele. Se ele falhar, ele será encantado por você até que o feitiço termine ou até que você ou seus companheiros causem dano a ele. A criatura encantada o considera um amigo próximo. Quando o feitiço termina, a criatura sabe que foi encantada por você.",
  "cure-wounds": "Uma criatura que você toca recupera um número de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração. Este feitiço não tem efeito em mortos-vivos ou constructos.",
  "detect-magic": "Por sua duração, você detecta a presença de magia dentro de 9 metros de você. Se você sentir magia dessa maneira, poderá usar sua ação para ver uma aura tênue em volta de qualquer criatura ou objeto visível que contenha magia, e você aprender sua escola de magia, se houver alguma.\nO feitiço pode penetrar a maioria das barreiras, mas é bloqueado por 30 cm de pedra, 2,5 cm de metal comum ou fino, uma fina folha de chumbo ou 90 cm de madeira ou terra.",
  "disguise-self": "Você faz com que pareça diferente até que o feitiço termine ou até usar sua ação para dispensá-lo. Você pode parecer até 30 cm mais curto ou mais alto e pode parecer gordo, magro ou entre eles. Você não pode mudar seu tipo de corpo, então você deve adotar uma forma que tenha o mesmo arranjo básico de membros. Caso contrário, a extensão da ilusão cabe a você.\nAs mudanças causadas por este feitiço falham em suportar inspeção física. Por exemplo, se você adicionar um chapéu à sua roupa, os objetos passarão pelo chapéu e qualquer pessoa que tocar nele sentirá a cabeça ou o cabelo. Se usar este feitiço para parecer mais magro do que é, a mão de alguém irá parar onde está de fato enquanto tenta chegar ao que parece ser seu braço.",
  "expeditious-retreat": "Este feitiço lhe permite mover-se com velocidade incrível. Quando você lança este feitiço, e então como uma ação bônus em cada um de seus turnos até que o feitiço termine, você pode tomar a ação Disparar.",
  "false-life": "Aproveitando um pálido facsímile de magia negra, você se concede uma medida de proteção da morte. Você ganha 1d4 + 4 pontos de vida temporários durante a duração.",
  "feather-fall": "Escolha até cinco criaturas caindo dentro do alcance. A taxa de descida de uma criatura caindo cai para 18 metros por turno até que o feitiço termine. Se a criatura pousar antes que o feitiço termine, ela não sofre dano de queda e pode pousar de pé, e o feitiço termina para essa criatura.",
  "find-familiar": "Você ganha os serviços de um familiar, um espírito que assume a forma de um animal de sua escolha: sapo, peixe dourado, falcão, coruja, gato, caranguejo, lagarto, polvo, rato, corvo, cobra do mar, aranha ou doninha. Aparecendo em um espaço desocupado dentro do alcance, o familiar tem as estatísticas de jogo da forma escolhida, embora seja um celestial, um elemental ou uma fada (à sua escolha) em vez de uma besta.\nSeu familiar age independentemente de você, mas sempre obedece às suas ordens. No combate, ele joga seu próprio turno de iniciativa e age de sua maneira própria. Um familiar não pode atacar, mas pode tomar outras ações normalmente.\nQuando o familiar cai a 0 pontos de vida, ele desaparece, sem deixar nenhum corpo físico para trás. Ele reaparece depois de você lançar este feitiço novamente. Como uma ação, você pode dispensar temporariamente seu familiar para um local bolso extradimensional. Alternativamente, você pode dispensar para sempre o familiar como uma ação, liberando-o de seu vínculo. Como uma ação enquanto seu familiar está temporariamente dispensado, você pode fazê-lo reaparecer em qualquer espaço desocupado dentro de 9 metros de você.",
  "fireball": "Um ponto brilhante de luz laranja dispara de seu dedo indicador em direção a um ponto que você escolhe dentro do alcance e explode em uma esfera de fogo de baixo rugido. Cada criatura em uma esfera de 6 metros centrada nesse ponto deve fazer um teste de resistência de Destreza. Um alvo sofre 8d6 de dano de fogo em caso de falha, ou metade desse dano em caso de êxito. O fogo se espalha ao redor dos cantos. Ele incendeia objetos inflamáveis na área que não estejam sendo carregados ou vestidos.",
  "fly": "Você toca uma criatura voluntária. O alvo ganha uma velocidade de voo de 18 metros durante a duração. Quando o feitiço termina, o alvo cai se ainda estiver voando, a menos que possa parar de cair por outros meios.",
  "haste": "Escolha uma criatura voluntária que você possa ver dentro do alcance. Até que o feitiço termine, a velocidade do alvo é dobrada, ele ganha um bônus de +2 para CA, tem vantagem em testes de resistência de Destreza e ganha uma ação adicional em cada um de seus turnos. Essa ação só pode ser usada para tomar as ações Atacar (apenas um ataque com arma), Disparar, Usar um Objeto, ou Dash.\nQuando o feitiço termina, o alvo não pode se mover ou realizar ações até depois de seu próximo turno, pois uma onda de letargia o domina.",
  "healing-word": "Uma criatura de sua escolha que você possa ver dentro do alcance recupera pontos de vida iguais a 1d4 + seu modificador de habilidade de conjuração. Este feitiço não tem efeito em mortos-vivos ou constructos.",
  "hold-person": "Escolha um humanoide que você possa ver dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Sabedoria ou ficará paralisado durante a duração. No final de cada um de seus turnos, o alvo pode fazer outro teste de resistência de Sabedoria. Em caso de sucesso, o feitiço termina no alvo.",
  "invisibility": "Uma criatura que você toca se torna invisível até que o feitiço termine. Qualquer coisa que o alvo esteja vestindo ou carregando é invisível enquanto estiver com o alvo. O feitiço termina para um alvo que atacar ou lançar um feitiço.",
  "lightning-bolt": "Um raio de relâmpago com uma largura de 1,5 metro e comprimento de 30 metros parte de você em uma direção de sua escolha. Cada criatura na linha deve fazer um teste de resistência de Destreza. Uma criatura sofre 8d6 de dano de relâmpago em caso de falha, ou metade desse dano em caso de êxito.\nO raio incendeia objetos inflamáveis na área que não estejam sendo carregados ou vestidos.",
  "mage-armor": "Você toca uma criatura voluntária que não esteja usando armadura, e uma proteção mágica protetora a envolve até que o feitiço termine. A CA base do alvo se torna 13 + seu modificador de Destreza. O feitiço termina se o alvo colocar armadura ou se você o dispensar como uma ação.",
  "magic-missile": "Você cria três dardos brilhantes de força mágica. Cada dardo atinge uma criatura de sua escolha que você possa ver dentro do alcance. Um dardo causa 1d4 + 1 de dano de força ao seu alvo. Os dardos todos atingem simultaneamente, e você pode direcioná-los para o mesmo alvo ou para alvos diferentes.",
  "shield": "Uma barreira invisível de força mágica aparece e protege você. Até o início do seu próximo turno, você tem um bônus de +5 para CA, inclusive contra o ataque desencadeante, e você não sofre dano de Míssil Mágico.",
  "sleep": "Este feitiço manda as criaturas para um sono mágico. Role 5d8; o total é quantos pontos de vida de criaturas este feitiço pode afetar. Criaturas dentro de 6 metros de um ponto que você escolher dentro do alcance são afetadas em ordem crescente de seus pontos de vida atuais (ignorando criaturas inconscientes).\nComeçando com a criatura que tem o menor número de pontos de vida atuais, cada criatura afetada por este feitiço fica inconsciente até que o feitiço termine, o adormecido tome dano ou alguém use uma ação para sacudir ou mofar o adormecido. Subtraia os pontos de vida de cada criatura do total antes de passar para a próxima criatura com o menor número de pontos de vida. O número de pontos de vida de uma criatura deve ser igual ou menor que o total restante para que essa criatura seja afetada.",
  "thunderwave": "Uma onda de energia trovejante parte de você. Cada criatura em um cubo de 4,5 metros originado de você deve fazer um teste de resistência de Constituição. Em caso de falha, uma criatura sofre 2d8 de dano de trovão e é empurrada até 3 metros de você. Em caso de êxito, a criatura sofre metade do dano e não é empurrada. Além disso, objetos não fixos que estejam completamente dentro da área são empurrados automaticamente 3 metros para longe de você pelo efeito do feitiço, e o feitiço emite um trovão que pode ser ouvido a até 90 metros.",
  "web": "Você conjura uma massa de teias grossas e pegajosas em um cubo de 6 metros originado de um ponto de sua escolha dentro do alcance. As teias duram durante a duração. As teias são um terreno difícil e leve o suficiente para bloquear visão.\nSe as teias não estiverem presas entre dois sólidos (como paredes ou árvores) ou dispostas no chão, em uma parede ou no teto, a massa de teias colabsada cai e o feitiço termina no início do seu próximo turno. As teias dispersas em uma superfície sólida têm profundidade de 1,5 metros.\nEm cada um de seus turnos dentro das teias, cada criatura começa seu turno ou entra nelas devendo ter sucesso em um teste de resistência de Destreza. Em caso de falha, ela fica restrita enquanto permanecer nas teias ou até escapar. Uma criatura restrita pelas teias pode usar sua ação para fazer um teste de Força contra sua CD de magia. Em caso de sucesso, ela não fica mais restrita.\nAs teias são inflamáveis. Qualquer cubo de 1,5 metro de teias exposto ao fogo se queima em 1 rodada, causando 2d4 de dano de fogo a qualquer criatura que comece seu turno na parte em chamas.",
  "wish": "Desejo é o feitiço mais poderoso que uma criatura mortal pode conjurar. Simplesmente falando em voz alta, você pode alterar os próprios fundamentos da realidade de acordo com seus desejos.\nO uso básico deste feitiço é duplicar qualquer outro feitiço de 8º nível ou menor. Você não precisa cumprir nenhum requisito desse feitiço, incluindo componentes caros. O feitiço simplesmente entra em vigor.\nAlternativamente, você pode criar um dos seguintes efeitos de sua escolha:\n• Você cria um objeto de até 25.000 po em valor que não seja um item mágico.\n• Você permite que até vinte criaturas que você possa ver recuperem todos os pontos de vida, e você encerra todos os efeitos nelas descritos no feitiço restauração superior.\n• Você concede resistência a um tipo de dano a até dez criaturas que você possa ver.\n• Você concede imunidade a um único feitiço ou outro efeito mágico por 8 horas a até dez criaturas que você possa ver.\n• Você desfaz um único evento recente forçando a relançada de qualquer jogada feita no último turno.",
  "zone-of-truth": "Você cria uma zona mágica que protege contra o engano em uma esfera de 4,5 metros de raio centrada em um ponto de sua escolha dentro do alcance. Até que o feitiço termine, uma criatura que entrar na área do feitiço pela primeira vez em um turno ou começar seu turno lá deve fazer um teste de resistência de Carisma. Em caso de falha, a criatura não pode pronunciar mentiras deliberadas enquanto estiver no raio. Você sabe se cada criatura é bem-sucedida ou falha em seu teste de resistência.\nUma criatura afetada está ciente do feitiço e pode, assim, evitar responder a perguntas às quais normalmente responderia com uma mentira. Tal criatura pode permanecer evasiva em suas respostas, desde que permaneça dentro dos limites da verdade.",
};

let updatedCount = 0;
const updated = spells.map(spell => {
  const newSpell = { ...spell };
  // Translate field values
  if (spell.casting_time) newSpell.casting_time = translateCastingTime(spell.casting_time);
  if (spell.range) newSpell.range = translateRange(spell.range);
  if (spell.duration) newSpell.duration = translateDuration(spell.duration);
  
  // Add Portuguese description
  if (PT_DESCRIPTIONS[spell.id]) {
    newSpell.description_pt = PT_DESCRIPTIONS[spell.id];
    updatedCount++;
  } else {
    // For spells without manual translation, keep original but mark as needing translation
    newSpell.description_pt = null;
  }
  return newSpell;
});

fs.writeFileSync(filePath, JSON.stringify(updated, null, 2), 'utf8');
console.log(`Updated ${updatedCount} spells with Portuguese descriptions`);
console.log(`Total spells: ${updated.length}`);
console.log(`Without PT description: ${updated.filter(s => !s.description_pt).length}`);
